apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: p-5crxt-namespaces-edit
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]