apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-member-promoted
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]